# Generated by Django 5.2.8 on 2025-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "dishes",
                    models.ManyToManyField(related_name="ingredients", to="menu.dish"),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
