# Generated by Django 6.0 on 2025-12-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_ingredient_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
